Repository JuliaParallel/Dagger.jl, pull requests merged in 2021-08, with the labels that each got.

#245 Don't mask IOError in fault handling
  Project.toml
  src/sch/Sch.jl
Labels: bug, fault handling

#247 Fix bug in lazy API state.errored check
  Project.toml
  src/sch/Sch.jl
  test/cache.jl
  test/runtests.jl
Labels: bug, scheduler

#230 DTable implementation
  Project.toml
  src/Dagger.jl
  src/table/dtable.jl
  src/table/iterators.jl
  src/table/operations.jl
  test/runtests.jl
  test/table.jl
Labels: enhancement, table interface, needs docs

#240 Add scopes mechanism to limit Chunk movement and restrict scheduling
  Project.toml
  docs/make.jl
  docs/src/scopes.md
  src/Dagger.jl
  src/chunks.jl
  src/sch/Sch.jl
  src/scopes.jl
  src/utils/clock.jl
  src/utils/system_uuid.jl
  test/processors.jl
  test/runtests.jl
  test/scopes.jl
  test/util.jl
Labels: enhancement, scheduler, data movement, needs docs

#251 Windows cputhreadtime fix and 32-bit fixes
  Project.toml
  src/sch/Sch.jl
  src/sch/eager.jl
  src/utils/clock.jl
Labels: bug

#252 Fix missing defs on MacOS, again...
  Project.toml
  src/utils/clock.jl
Labels: bug

#258 Fix eager API thunk retention
  Project.toml
  src/sch/Sch.jl
  src/sch/dynamic.jl
  src/sch/eager.jl
  src/sch/fault-handler.jl
  src/sch/util.jl
  src/thunk.jl
Labels: bug, scheduler, eager api

#264 Fix task stalls due to deserialization errors
  Project.toml
  src/sch/Sch.jl
  test/thunk.jl
Labels: bug, error handling, eager api
