Repository JuliaParallel/Dagger.jl, pull requests merged in 2022-04, with the labels that each got.

#342 add_thunk: Optimize domination check
  src/sch/dynamic.jl
  src/sch/util.jl
  test/options.jl
  test/scheduler.jl
Labels: bug, scheduler, performance

#337 Context: Add global context for lazy API
  lib/DaggerWebDash/src/d3.jl
  src/array/darray.jl
  src/compute.jl
  src/file-io.jl
  src/processor.jl
  src/ui/graph.jl
Labels: needs tests, scheduler, needs docs, contexts

#343 Switch to new TagBot
  .github/workflows/TagBot.yml
Labels: ci

#345 spawn: Disallow passing Thunk as argument
  src/thunk.jl
  test/thunk.jl
Labels: bug, scheduler
