Repository JuliaParallel/Dagger.jl, pull requests merged in 2023-08, with the labels that each got.

#413 TEST: Try implementing custom actions
  .github/workflows/CustomCommands.yml
  benchmarks/suites/nmf.jl
Labels: ci

#417 Requires-ify UI deps
  Manifest.toml
  Project.toml
  src/Dagger.jl
  src/ui/graph-core.jl
  src/ui/graph.jl
  test/logging.jl
Labels: enhancement, dependencies

#419 Add File and tofile helpers
  Project.toml
  docs/src/index.md
  src/file-io.jl
  src/sch/Sch.jl
  test/file-io.jl
  test/runtests.jl
Labels: enhancement, file io, data movement

#418 Update Dagger README.md docs with a use case sceanario
  README.md
  docs/Manifest.toml
  docs/make.jl
  docs/src/index.md
  docs/src/use-cases/parallel-nested-loops.md
Labels: documentation

#428 Use ScopedValues instead of ContextVariablesX
  .buildkite/pipeline.yml
  .github/workflows/Documentation.yml
  Manifest.toml
  Project.toml
  src/Dagger.jl
  src/options.jl
Labels: enhancement, upstream
