Repository JuliaParallel/Dagger.jl, pull requests merged in 2024-07, with the labels that each got.

#540 Add render/show_logs to chrome_trace
  Project.toml
  docs/src/logging-visualization.md
  ext/JSON3Ext.jl
  src/Dagger.jl
  test/Project.toml
  test/logging.jl
Labels: logging, visualization

#551 docs: Create favicon and add it to the documentation
  README.md
  docs/logo.svg
  docs/make.jl
  docs/src/assets/favicon.ico
  docs/src/assets/logo-with-text.jpg
  docs/src/assets/logo-with-text.svg
  docs/src/assets/logo.svg
Labels: documentation

#553 @spawn: Properly rethrow in @sync
  src/thunk.jl
  test/thunk.jl
Labels: bug, eager api

#556 `@spawn`: Support NamedTuple construction and access
  src/thunk.jl
  test/thunk.jl
Labels: eager api

#555 Add fetch_all recursive helper
  Project.toml
  src/Dagger.jl
  src/chunks.jl
  src/thunk.jl
  test/thunk.jl
Labels: eager api

#554 More `Thunk` to `DTask` renames
  docs/src/api-dagger/functions.md
  docs/src/darray.md
  docs/src/scopes.md
  src/array/alloc.jl
  src/array/cholesky.jl
  src/dtask.jl
  src/sch/Sch.jl
  src/sch/dynamic.jl
  src/sch/eager.jl
  src/sch/util.jl
  src/submission.jl
  src/task-tls.jl
  src/thunk.jl
  test/datadeps.jl
  test/mutation.jl
  test/processors.jl
  test/scheduler.jl
  test/scopes.jl
  test/thunk.jl
Labels: error handling, eager api
