Repository JuliaParallel/Dagger.jl, pull requests merged in 2024-04, with the labels that each got.

#498 Remove more invalidations
  src/lib/domain-blocks.jl
Labels: latency

#493 Add options docstrings to the docs
  docs/src/api-dagger/types.md
  docs/src/scheduler-internals.md
  docs/src/task-spawning.md
  src/eager_thunk.jl
  src/sch/Sch.jl
Labels: documentation

#492 DArray: Implement efficient in-place matrix-matrix multiply
  .buildkite/pipeline.yml
  Project.toml
  docs/src/darray.md
  src/Dagger.jl
  src/array/copy.jl
  src/array/darray.jl
  src/array/getindex.jl
  src/array/indexing.jl
  src/array/matrix.jl
  src/array/mul.jl
  src/array/operators.jl
  src/array/setindex.jl
  src/lib/domain-blocks.jl
  src/memory-spaces.jl
  src/submission.jl
  test/Project.toml
  test/array/copies.jl
  test/array/core.jl
  test/array/linalg/cholesky.jl
  test/array/linalg/matmul.jl
  test/array/mapreduce.jl
  test/imports.jl
  test/linalg.jl
  test/logging.jl
  test/runtests.jl
  test/scheduler.jl
Labels: enhancement, array interface

#500 Add num_processors helper
  src/utils/scopes.jl
  test/processors.jl
  test/scopes.jl
Labels: processors

#502 precompile: Don't let throwto hang the root task
  src/precompile.jl
Labels: bug
